### ISSUE TITLE
Is there a method to reload schema file of existing database?

### ISSUE THREAD

**Issue by elliesch** [BDNYC/astrodbkit#100]
I have used astrodbkit to create an existing and populated database. I have edited my schema file to include a new type of table. How do I acknowledge this update in astrodbkit?

**Comment by hover2pi** [comment]
You can add a table with the `db.table(new_table=True)` method and supply the column names, types, constraints, etc. Do `db.table?` for the docstring. When you run `db.save()` it should update the schema. Let me know if that works!


- Joe


Joe Filippazzo, Ph.D.
Senior Research and Instrument Analyst
Space Telescope Science Institute
(410) 338-6871

________________________________

**Comment by elliesch** [comment]
@dr-rodriguez @hover2pi thank you for your help! I initially tried modifying the schema file outside of astrodbkit and reloading upon open, but it doesn't load the changes I've made to the SQL file. How do I edit an existing table using astrodbkit?

**Comment by dr-rodriguez** [comment]
If astrodbkit isn't loading SQL changes then that's a bug we need to fix. If you can provide more details that would be good.

There is a hacky way I've used to update tables in https://github.com/BDNYC/BDNYCdevdb/blob/master/scripts/set_foreign_keys.py, but `db.table()` is made for this. I can't recall why I didn't use that (maybe it doesn't handle column renaming?).

**Comment by elliesch** [comment]
Maybe I'm not loading the schema correctly? I tried using astrodb.Database('db_path', 'updated_schema_path')

I'm trying to update to this table
```SQL
CREATE TABLE spectral_templates (
	id INTEGER NOT NULL UNIQUE,
	shortname TEXT UNIQUE NOT NULL,
	spectrum SPECTRUM NOT NULL,
	wavelength_units TEXT ,
	flux_units TEXT ,
	wavelength_order INTEGER ,
	regime TEXT ,
	publication_shortname TEXT ,
	filename TEXT ,
	comments TEXT ,
	version REAL ,
	local_spectrum SPECTRUM ,
	PRIMARY KEY(id, shortname),
	FOREIGN KEY (publication_shortname) REFERENCES publications (shortname) ON UPDATE CASCADE
);
```

This is the original table that I have
``` SQL
CREATE TABLE `spectral_templates` (
	`id`	INTEGER NOT NULL UNIQUE,
	`source_id`	INTEGER,
	`spectrum`	SPECTRUM NOT NULL,
	`wavelength_units`	TEXT,
	`flux_units`	TEXT,
	`wavelength_order`	INTEGER,
	`regime`	TEXT,
	`publication_shortname`	TEXT,
	`filename`	TEXT,
	`comments`	TEXT,
	`version`	REAL,
	`local_spectrum`	SPECTRUM,
	FOREIGN KEY(`source_id`) REFERENCES `sources`(`id`) ON UPDATE CASCADE,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`publication_shortname`) REFERENCES `publications`(`shortname`) ON UPDATE CASCADE
);
```

I can't figure out how to do this with `db.table()` either.

**Comment by dr-rodriguez** [comment]
Try calling astrodbkit with `astrodb.Database('updated_schema_path')` that is, don't refer to the original db file/location at all. The second parameter in `astrodb.Database()` is the directory in which the individual tables are stored (by default tabledata/)

**Comment by elliesch** [comment]
That did it! Thank you so much for explaining why. This means there is no bug, and it loads the updated schema and works now!
