### ISSUE TITLE
add band info to photometry table

### ISSUE THREAD

**Issue by kelle** [BDNYC/astrodbkit#13]
add central wavelength and wavelength window to phot table. Maybe even make a lookup table for each band with link to passband function.

**Comment by kelle** [comment]
change 'band' to 'band_id' and make look up table with band info.

**Comment by dr-rodriguez** [comment]
I would recommend leaving band (or change to band_name) and have band_id as an additional separate column.

**Comment by hover2pi** [comment]
Closing this and putting it in the BDNYCdb repo.

**Comment by kelle** [comment]
https://github.com/BDNYC/BDNYCdb/issues/2
