### ISSUE TITLE
SQL IN operator

### ISSUE THREAD

**Issue by dr-rodriguez** [BDNYC/astrodbkit#14]
The SQL IN operator appears to not be working. For example: 
'SELECT * FROM photometry WHERE band IN ("J","H")'
should work to grab all the J and H band photometry.

**Comment by hover2pi** [comment]
It works on my end. Note that I changed the band names to the more explicit '2MASS_J', 'MKO_H', etc. So this does work for me: "SELECT * FROM photometry WHERE band IN ('2MASS_J','2MASS_H')"

Let me know if it persists!
