### ISSUE TITLE
Error in explicit query

### ISSUE THREAD

**Issue by dr-rodriguez** [BDNYC/astrodbkit#22]
When running a query joining two instances of the same table, explicit_query will fail with a ValueError. 
For example, the following attempts to create a J-H column, but fails:
```
SELECT p1.magnitude-p2.magnitude FROM photometry AS p1 
JOIN photometry AS p2 ON p1.source_id=p2.source_id 
WHERE p1.band='J' AND p2.band='H'
```

**Comment by hover2pi** [comment]
I added a work around so this doesn't fail. It's not perfect but it'll work for any internal table joins like this.
