### ISSUE TITLE
sources with non-useable spex prism spectrum

### ISSUE THREAD

**Issue by paigegiorlagodfrey** [BDNYC/astrodbkit#24]
Several sources have an issue with their SpeX Prism (instrument_id=6 and mode_id=1) spectrum. They are either unable to plot (perhaps the file path is wrong?) or their spectrum.data length exceeds w,f,e.

**Comment by kelle** [comment]
this ticket belongs in the BDNYCdb repo https://github.com/BDNYC/BDNYCdb/issues/
