### ISSUE TITLE
first code release and numbering scheme

### ISSUE THREAD

**Issue by kelle** [BDNYC/astrodbkit#28]
I thought we already took care of this...there should be a release (and a zenodo record).
I vote it just be version 1.0. as the version associated with the submitted paper. as small things are modified, versions can increase to 1.1, 1.2 and so on.

**Comment by dr-rodriguez** [comment]
I don't think astrodbkit is ready to be version 1.0 yet, but I did a (pre-)release for the current version: 0.5. 
No zenodo record yet, though.

**Comment by kelle** [comment]
How can we not have a Zenodo record yet?!?

**Comment by kelle** [comment]
shouldn't astrodbkit always be cited alongside the database? YES! our implementation of the database doesn't function without  astrodbkit. We need a Zenodo record ASAP. @dr-rodriguez @hover2pi  Which one of you want to do it?

**Comment by dr-rodriguez** [comment]
I'll look into this.

**Comment by dr-rodriguez** [comment]
Done for new release 0.6.6: 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1155843.svg)](https://doi.org/10.5281/zenodo.1155843)
