### ISSUE TITLE
possible bug in path to spectra

### ISSUE THREAD

**Issue by kelle** [BDNYC/astrodbkit#45]
Merge function looking for data in nir_spectra directory but I'm pretty sure the modified records correspond to optical spectra.

```python
db.merge('/Users/kelle/Dropbox/BDNYCdev_kcApr16.db',tables=["spectra"])
Could not retrieve spectrum at /Users/kelle/Dropbox/BDNYC_spectra/nir_spectra/U20744.fits.
Could not retrieve spectrum at /Users/kelle/Dropbox/BDNYC_spectra/nir_spectra/U10802.fits.
```

**Comment by kelle** [comment]
not a bug, just something which needs to be fixed in the fields.

**Comment by kelle** [comment]
should probably do a systematic check of filenames for spectra with OPT regime.

**Comment by dr-rodriguez** [comment]
Not relevant for astrodbkit, moved to https://github.com/BDNYC/BDNYCdevdb/issues/43
