### ISSUE TITLE
spectrum.data has length 8 for some objects

### ISSUE THREAD

**Issue by paigegiorlagodfrey** [BDNYC/astrodbkit#51]
Something wrong in what is stored as the spectrum?

**Comment by kelle** [comment]
please include enough info to replicate the problem. spectrum_id for
example.

On Mon, May 23, 2016 at 3:00 PM, paigegiorlagodfrey <
notifications@github.com> wrote:

> Something wrong in what is stored as the spectrum?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BDNYC/astrodbkit/issues/51>
>



-- 
Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by paigegiorlagodfrey** [comment]
An example is spectrum_id=2728.

Hmmmm, a new observation has come my way. If I pull all of the t dwarf spex spectra out, including 2728, I get normal spectrum.data of length 3. If I query for one spectrum, like 2728, I get spectrum.data of length 8.

**Comment by hover2pi** [comment]
You mean if you query for just 2728 it doesn't work but if you query for multiple spectra, it works?

**Comment by paigegiorlagodfrey** [comment]
Yes, if I do a batch query for all T dwarfs I get spectra of length 3, but if I query for one particular object I get length 8. Using an L dwarf at the moment,
spectrum_0355=db.query("select spectrum from spectra where source_id=700 and inst_id=6 and mode_id=1",unpack=True)
spectrum_0355=db.query("select spectrum from spectra where source_id=700 and instrument_id=6 and mode_id=1",unpack=True)

both of those return spectrum_0355.data of length 8.

**Comment by paigegiorlagodfrey** [comment]
Not a bug! Just the way it is extracted in a single query versus a batch query.
