### ISSUE TITLE
T dwarf data has spectra not retrievable

### ISSUE THREAD

**Issue by paigegiorlagodfrey** [BDNYC/astrodbkit#52]
This query,
a=db.query("select s.id,s.spectrum from spectra as s join spectral_types as st on st.source_id=s.source_id where st.spectral_type between 20 and 29 and st.regime='IR' and st.adopted=1 and s.instrument_id=6 and s.mode_id=1",unpack=True)

returns a list of spectra with incorrect paths that specify /Users/Joe/Dropbox:

/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ015010.89+382724.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ081958.05-033528.5_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ162725.65+325524.6_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ185215.76+353716.7_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ061135.13-041024.0_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ013836.58-032221.2_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ022322.36-293257.2_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ030724.59+290447.4_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ041054.48+141131.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ044853.28-193548.6_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ052536.35+673952.6_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ062720.07-111428.0_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ065609.59+420531.9_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ082131.64+144319.2_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ095259.29+195508.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ101905.62+652954.2_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ145715.03+581510.2_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ162208.93-095934.4_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ172844.93+571642.7_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ190624.74+450807.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ221354.68+091139.4_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ223729.52-061434.4_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ223937.55+161716.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ231939.14-184404.4_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ234026.61-074508.1_SpeX.txt.
/Users/Joe/Dropbox/BDNYC_Shared/Paige/SpeX_prism/Kirkpatrick2011/WISEJ234841.10-102844.1_SpeX.txt.

**Comment by kelle** [comment]
Paige, I suggest you fix this yourself. The path should be something like $BDNYC_spectra/Spex/Prism. The copy, modify, merge workflow should work for this fix.

**Comment by paigegiorlagodfrey** [comment]
Copied and modified. Not merged yet.

**Comment by paigegiorlagodfrey** [comment]
Fixed in Dropbox version 16 and noted in changelog manually with id 8.
