### ISSUE TITLE
Error when Adding Data (type mismatch in metadata)

### ISSUE THREAD

**Issue by dr-rodriguez** [BDNYC/astrodbkit#53]
When adding data to tables (either new or existing), a TableMergeError may be returned: 
`TableMergeError: The 'components' columns have incompatible types: ['string512', 'int64']`

This happens when you attempt to add, for example, new sources and specify the companion and/or components table:
`db.add_data([['ra','dec','companions'],[12, -23, 67]], 'sources')`

Astropy will assume these columns are of type int (as they generally contain only a single source_id) and will then fail to merge them as the existing table has these columns specified as text/strings. The error is technically raised by astropy when injecting the data to the table, but it may be possible for us to fix this.

**Comment by hover2pi** [comment]
I added an AttributeError exception to this since it was failing on legit data additions to the publications table.
