### ISSUE TITLE
Update db.adddata method to accept Astropy tables

### ISSUE THREAD

**Issue by emilurice** [BDNYC/astrodbkit#59]
Possibly related to Issue #20

**Comment by dr-rodriguez** [comment]
Is this strictly necessary? If you want to save the rows of an astropy table, you can already add them with add_data. The entire table can be saved with something like:
```
data = list()
data.append(t.colnames) # t is the astropy table
data += t.as_array().tolist()
db.add_data(data, tablename)
```
As long as the column names match, this would work to add the table to the database.

Or is the issue referring to adding a full table as a single entry in the database?

**Comment by hover2pi** [comment]
Yeah, it's not necessary. It was suggested by the referee on the astrodbkit
paper and seemed useful but definitely not essential.

**Comment by dr-rodriguez** [comment]
Closing as it was deemed not essential. Re-open if it becomes necessary.
