### ISSUE TITLE
Inventory method failing on tables with unicode characters

### ISSUE THREAD

**Issue by hover2pi** [BDNYC/astrodbkit#6]
astropy.io.ascii.write() method breaks on spectral types table when trying to print beta or gamma.

**Comment by kelle** [comment]
@dr-rodriguez Can you take a look?

**Comment by dr-rodriguez** [comment]
This is a known bug in astropy.io.ascii that's present for Py2; see [here](https://github.com/astropy/astropy/issues/3826). 
I've coded a simple workaround for this so this should work now, though the formatting may not be exactly the same as astropy.io.ascii.write().

**Comment by hover2pi** [comment]
I merged the PR and the workaround is printing the same record a bunch of times. I'm looking at it now.
 
![screen shot 2016-04-18 at 9 06 54 pm](https://cloud.githubusercontent.com/assets/34687/14624579/f734f2f4-05a9-11e6-8f99-02036a68d839.png)

**Comment by dr-rodriguez** [comment]
Fixed. Had [0] in the for loop so it would keep repeating the first element. Didn't catch that when I tested it.

**Comment by hover2pi** [comment]
Oops. I didn't see this. I just fixed it too!
