### ISSUE TITLE
Errors when trying to plot spectra

### ISSUE THREAD

**Issue by ECGonzales** [BDNYC/astrodbkit#60]
When using db.plot_spectrum()
 When trying to plot spectra id 8072:   ValueError: Keyword 'END' not allowed.

When trying to plot spectra id 2647:
ValueError: FITS header values must contain standard printable ASCII characters; 
'\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\r' 
contains characters/bytes that do not represent printable characters in ASCII.

Could not plot spectrum 1170

**Comment by dr-rodriguez** [comment]
I just tried this and had no problem grabbing and plotting spectra 8072 and 1170. Are you running the latest version of astrodbkit?

I could not grab 2647 as the database is trying to find a file called spex_prism_W1147-2040_Schn16.txt but the file itself appears to have been moved or renamed.
