### ISSUE TITLE
build database from text files rather than loading a .db file

### ISSUE THREAD

**Issue by kelle** [BDNYC/astrodbkit#63]
This conversation was started over email and I'm moving it here.

@hover2pi said:

> astrodbkit users can now instantiate the astrodb.Database() class by pointing to a .sql (or .db) file in a Github repo on their machine (e.g. astrodb.Database('/Users/me/Modules/BDNYCdevdb/BDNYCdev.sql')). It creates a .db file of the same name and loads it into a variable (e.g. db) and it's business as usual.
> 
> When a user wants to write changes, no matter how big or small, they run db.save(branch='master'). It then asks for a username and commit message, synchs with the git repo, then pushes the changes to the .sql file ONLY, all without leaving the Python session. The .sql file is just text so all changes are version controlled in Github.
> 
> When the user is all done, they can run db.close and it asks if they want to delete the .db file because a fresh one will be generated next time.
> 
> There are problems, I'm sure, but I like it already. It's on the 'build_db' branch if you want to check it out. 
> 
> Let me know what you think!
>

**Comment by kelle** [comment]
This is awesome! So glad the github integration was straightforward.

I'm not familiar with .sql files. Does that include all the tables and the schema? So will we be doing version control on one big text .sql file or on one file per table + a schema file?

**Comment by dr-rodriguez** [comment]
I had a look at it and the .sql file is an ascii file with the schema and a bunch of INSERT INTO commands to populate the database. So it has both schema and data in a single file.

**Comment by hover2pi** [comment]
I did. I actually just changed it so that there is a schema file and a directory of files with data for each table. This is so that file sizes are smaller and changes can be seen on this website. Also, distributing the data like this will avoid reaching file size limits for much longer as the database grows.
