### ISSUE TITLE
support subqueries?

### ISSUE THREAD

**Issue by kelle** [BDNYC/astrodbkit#96]
I'm trying to use EXIST to identify sources with at least one published spectral type but I'm getting a syntax error from the astrodbkit query function. Does astrodbkit support subqueries?  Here is the example I'm following:
https://stackoverflow.com/questions/3197322/sql-query-at-least-one-of-something
And this is my query which is not working:

`db.query("SELECT sources.id FROM sources WHERE (sources.version >= 1 AND EXISTS (SELECT NULL FROM spectral_types WHERE spectral_types.source_id = sources.id AND spectral_types.version >= 1))", fmt='pandas')`

And here's the error:
```
Traceback (most recent call last):
  File "/Users/kelle/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.4127.16/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/kelle/Dropbox/BDNYCdevdb/scripts/spectral_types_to_v2.py", line 29, in <module>
    needtobepubd = db.query("SELECT sources.id FROM sources WHERE EXISTS (SELECT NULL FROM spectral_types WHERE spectral_types.source_id = sources.id AND spectral_types.version >= 1))", fmt='pandas')
  File "/Users/kelle/anaconda/envs/bdnycdb/lib/python2.7/site-packages/astrodbkit/astrodb.py", line 1320, in query
    dictionary = self.dict(SQL, params).fetchall()
OperationalError: near ")": syntax error
```

**Comment by dr-rodriguez** [comment]
Just tried the query you posted and it worked for me (with a warning about converters). Are you running the latest version of astrodbkit? 
Even if you're not, when you get errors like these try running queries with `use_converters=False` and see if that changes anything. By default, db.query tries to use the converters (eg, to get spectra as type `Spectrum`) and can run into issues when re-writing the query.

**Comment by kelle** [comment]
I was not using the latest version -- thanks!  

If that doesn't fix it, I'll try to mess with `use_converters`.

**Comment by kelle** [comment]
updating fixed the problem.
